{{
    config(
        materialized = "view"
    )
}}
with stg_lead as (
    select *
    from {{ ref('stg_salesforce__lead') }}
)
select
    {{ dbt_utils.generate_surrogate_key(['lead_id']) }} as lead_key,
    lead_id as salesforce_lead_id,
    isdeleted,
    masterrecordid,
    salutation,
    firstname,
    lastname,
    title,
    company,
    street,
    city,
    state,
    postalcode,
    country,
    latitude,
    longitude,
    geocodeaccuracy,
    phone,
    mobilephone,
    fax,
    email,
    website,
    description,
    leadsource,
    status,
    industry,
    rating,
    annualrevenue,
    numberofemployees,
    ownerid,
    hasoptedoutofemail,
    isconverted,
    converteddate,
    convertedaccountid,
    convertedcontactid,
    convertedopportunityid,
    isunreadbyowner,
    createddate,
    createdbyid,
    lastmodifieddate,
    lastmodifiedbyid,
    systemmodstamp,
    lastactivitydate,
    donotcall,
    hasoptedoutoffax,
    lasttransferdate,
    jigsaw,
    jigsawcontactid,
    cleanstatus,
    companydunsnumber,
    dandbcompanyid,
    emailbouncedreason,
    emailbounceddate,
    individualid,
    pronouns,
    genderidentity,
    siccode__c as siccode,
    productinterest__c as productinterest,
    primary__c as primary,
    currentgenerators__c as currentgenerators,
    numberoflocations__c as numberoflocations
from stg_lead