{{
    config(
        materialized = "view"
    )
}}

with stg_account as (
    select *
    from {{ ref('stg_salesforce__acount') }}
)
select
    {{ dbt_utils.generate_surrogate_key(['account_id']) }} as account_key,
    account_id as salesforce_account_id,
    isdeleted,
    masterrecordid,
    name,
    type,
    parentid,
    billingstreet,
    billingcity,
    billingstate,
    billingpostalcode,
    billingcountry,
    billinglatitude,
    billinglongitude,
    billinggeocodeaccuracy,
    shippingstreet,
    shippingcity,
    shippingstate,
    shippingpostalcode,
    shippingcountry,
    shippinglatitude,
    shippinglongitude,
    shippinggeocodeaccuracy,
    phone,
    fax,
    accountnumber,
    website,
    sic,
    industry,
    annualrevenue,
    numberofemployees,
    ownership,
    tickersymbol,
    description,
    rating,
    site,
    ownerid,
    createddate,
    createdbyid,
    lastmodifieddate,
    lastmodifiedbyid,
    systemmodstamp,
    lastactivitydate,
    jigsaw,
    jigsawcompanyid,
    cleanstatus,
    accountsource,
    dunsnumber,
    tradestyle,
    naicscode,
    naicsdesc,
    yearstarted,
    sicdesc,
    dandbcompanyid,
    operatinghoursid,
    customerpriority__c as customerpriority,
    sla__c as sla,
    active__c as active,
    numberoflocations__c as numberoflocations,
    upsellopportunity__c as upsellopportunity,
    slaserialnumber__c as slaserialnumber,
    slaexpirationdate__c as slaexpirationdate
from stg_account